apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: log-httpserver
  namespace: httpserver
spec:
  storageClassName: rook-ceph-block
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi