apiVersion: v1
kind: Service
metadata:
  name: cantevenl-httpserver-svc
  namespace: httpserver
  labels:
    app: httpserver
spec:
  ports:
    - port: 80
      protocol: TCP
      name: http
      targetPort: 8080
  selector:
    app: httpserver
  type: ClusterIP